name: shoesly
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7
  intl: ^0.19.0
  lottie: ^3.1.2
  fluttertoast: ^8.2.5
  flutter_rating_bar: ^4.0.1
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Thin.ttf
        weight: 100
      - asset: assets/fonts/Inter-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Inter-Light.ttf
        weight: 300
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Inter-Black.ttf
        weight: 900
